### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility on just typing help.

### ISSUE THREAD

**Issue by nadzhou** [spiwokv/tltsne#3]
My specs: 

> Ubuntu 21.04
> Python 3.8

```
   % tltsne -h                                                 
  Traceback (most recent call last):
    File "/home/nadzhou/anaconda3/bin/tltsne", line 14, in <module>
      import tltsne
    File "/home/nadzhou/anaconda3/lib/python3.8/site-packages/tltsne/__init__.py", line 20, in <module>
      import pyemma.coordinates as coor
    File "/home/nadzhou/anaconda3/lib/python3.8/site-packages/pyemma/__init__.py", line 34, in <module>
      from . import msm
    File "/home/nadzhou/anaconda3/lib/python3.8/site-packages/pyemma/msm/__init__.py", line 83, in <module>
      from msmtools.analysis.dense.pcca import PCCA
    File "/home/nadzhou/anaconda3/lib/python3.8/site-packages/msmtools/__init__.py", line 41, in <module>
      from . import estimation
    File "/home/nadzhou/anaconda3/lib/python3.8/site-packages/msmtools/estimation/__init__.py", line 91, in <module>
      from .api import *
    File "/home/nadzhou/anaconda3/lib/python3.8/site-packages/msmtools/estimation/api.py", line 38, in <module>
      from . import dense
    File "/home/nadzhou/anaconda3/lib/python3.8/site-packages/msmtools/estimation/dense/__init__.py", line 24, in <module>
      from .mle import mle_trev, mle_trev_given_pi
    File "msmtools/estimation/dense/mle/mle_trev.pyx", line 1, in init msmtools.estimation.dense.mle.mle_trev
  ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```

**Comment by fazekaszs** [comment]
Same here:
```
Traceback (most recent call last):
  File "/rhome/PROTMOD/fazekaszs/miniconda3/bin/tltsne", line 14, in <module>
    import tltsne
  File "/rhome/PROTMOD/fazekaszs/miniconda3/lib/python3.8/site-packages/tltsne/__init__.py", line 20, in <module>
    import pyemma.coordinates as coor
  File "/rhome/PROTMOD/fazekaszs/miniconda3/lib/python3.8/site-packages/pyemma/__init__.py", line 34, in <module>
    from . import msm
  File "/rhome/PROTMOD/fazekaszs/miniconda3/lib/python3.8/site-packages/pyemma/msm/__init__.py", line 83, in <module>
    from msmtools.analysis.dense.pcca import PCCA
  File "/rhome/PROTMOD/fazekaszs/miniconda3/lib/python3.8/site-packages/msmtools/__init__.py", line 41, in <module>
    from . import estimation
  File "/rhome/PROTMOD/fazekaszs/miniconda3/lib/python3.8/site-packages/msmtools/estimation/__init__.py", line 91, in <module>
    from .api import *
  File "/rhome/PROTMOD/fazekaszs/miniconda3/lib/python3.8/site-packages/msmtools/estimation/api.py", line 38, in <module>
    from . import dense
  File "/rhome/PROTMOD/fazekaszs/miniconda3/lib/python3.8/site-packages/msmtools/estimation/dense/__init__.py", line 24, in <module>
    from .mle import mle_trev, mle_trev_given_pi
  File "msmtools/estimation/dense/mle/mle_trev.pyx", line 1, in init msmtools.estimation.dense.mle.mle_trev
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

My specs:

> openSUSE Leap 15.3
> Python 3.8.5

I installed it using:

> pip install git+https://github.com/spiwokv/tltsne@master
